DROP TABLE SOPORTE_INGRESO;
DROP TABLE SOPORTE_GASTO;
DROP TABLE INGRESO;
DROP TABLE GASTO;
DROP TABLE FUENTE;
DROP TABLE CONCEPTO_INGRESO;
DROP TABLE CONCEPTO_GASTO;
DROP TABLE USUARIO;

CREATE TABLE USUARIO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NOMBRE VARCHAR(200),
	CEDULA VARCHAR(200),
    CORREO VARCHAR(200),
    CARGO VARCHAR(200),
    CONTRASENA VARCHAR(200),
    
    CONSTRAINT PK_USUARIO PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE INGRESO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    FECHA DATE,
    EMPRESA VARCHAR(200),
    CANTIDAD INTEGER,
    VALORUNITARIO INTEGER,
    VALORTOTAL INTEGER,
    IDFUENTE INTEGER,
    IDCONCEPTO INTEGER,
    IDUSUARIO INTEGER,
    
    CONSTRAINT PK_GASTO PRIMARY KEY(IDENTIFICADOR)
);

CREATE TABLE GASTO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    FECHA DATE,
    EMPRESA VARCHAR(200),
    VALORTOTAL INTEGER,
    IDCONCEPTO INTEGER,
    IDFUENTE INTEGER,
    IDUSUARIO INTEGER,
    
    CONSTRAINT PK_GASTO PRIMARY KEY(IDENTIFICADOR)
);

CREATE TABLE CONCEPTO_INGRESO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NOMBRE VARCHAR(200),
    
    CONSTRAINT PK_CONCEPTO_INGRESO PRIMARY KEY (IDENTIFICADOR)
);
CREATE TABLE CONCEPTO_GASTO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NOMBRE VARCHAR(200),
    
    CONSTRAINT PK_CONCEPTO_GASTO PRIMARY KEY (IDENTIFICADOR)
);
CREATE TABLE FUENTE(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NOMBRE VARCHAR(200),
    
    CONSTRAINT PK_FUENTE PRIMARY KEY (IDENTIFICADOR)
);

CREATE TABLE SOPORTE_INGRESO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NUMERO VARCHAR(200),
    ARCHIVO BLOB,
    IDINGRESO INTEGER,
    
    CONSTRAINT PK_SOPORTE_INGRESO PRIMARY KEY(IDENTIFICADOR)
);

CREATE TABLE SOPORTE_GASTO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NUMERO INTEGER,
    ARCHIVO BLOB,
    IDGASTO INTEGER,
    
    CONSTRAINT PK_SOPORTE_GASTO PRIMARY KEY(IDENTIFICADOR)
);

/**
	BLOQUE DE CODIGO PARA LAS CLAVES FORANEAS ENTRE TABLAS
*/
ALTER TABLE INGRESO ADD CONSTRAINT FK_INGRESO_FUENTE FOREIGN KEY (IDFUENTE) REFERENCES FUENTE(IDENTIFICADOR);
ALTER TABLE INGRESO ADD CONSTRAINT FK_INGRESO_CONCEPTO FOREIGN KEY (IDCONCEPTO) REFERENCES CONCEPTO(IDENTIFICADOR);
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_FUENTE FOREIGN KEY (IDFUENTE) REFERENCES FUENTE(IDENTIFICADOR);
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_CONCEPTO FOREIGN KEY (IDCONCEPTO) REFERENCES GASTO(IDENTIFICADOR);

ALTER TABLE INGRESO ADD CONSTRAINT FK_INGRESO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDENTIFICADOR);
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDENTIFICADOR);

ALTER TABLE SOPORTE_GASTO ADD CONSTRAINT FK_SOPORTE_GASTO_GASTO FOREIGN KEY (IDGASTO) REFERENCES GASTO(IDENTIFICADOR);
ALTER TABLE SOPORTE_INGRESO ADD CONSTRAINT FK_SOPORTE_INGRESO_INGRESO FOREIGN KEY (IDINGRESO) REFERENCES INGRESO(IDENTIFICADOR);

ALTER TABLE INGRESO DROP FOREIGN KEY FK_INGRESO_CONCEPTO;
ALTER TABLE GASTO DROP FOREIGN KEY FK_GASTO_CONCEPTO;

ALTER TABLE INGRESO ADD CONSTRAINT FK_INGRESO_CONCEPTO FOREIGN KEY(IDCONCEPTO) REFERENCES CONCEPTO_INGRESO(IDENTIFICADOR);
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_CONCEPTO FOREIGN KEY(IDCONCEPTO) REFERENCES CONCEPTO_GASTO(IDENTIFICADOR);
